name: app
description: Howdy - Your way to connect with friends.
publish_to: 'none'
version: 0.8.4+142

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  loading_animation_widget: ^1.2.0+4
  camera: ^0.10.5+3
  http: ^1.1.0
  connectivity_plus: ^4.0.2
  flutter_secure_storage: ^8.0.0
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  image_picker: ^1.0.4
  firebase_core: ^2.7.0
  firebase_messaging: ^14.6.8
  flutter_search_bar: ^3.0.0-dev.1
  webview_flutter: ^2.0.13
  feather_icons: ^1.2.0
  flutter_notion_avatar: ^0.0.4
  avataaars: ^0.5.1
  flex_color_picker: ^3.3.0
  flutter_svg: ^2.0.7
  aptabase_flutter: ^0.1.0
  font_awesome_flutter: ^10.5.0
  package_info_plus: ^4.1.0
  flutter_chat_ui: ^1.6.9
  flutter_chat_types: ^3.6.2
  screenshot_callback: ^3.0.1
  socket_io_client: ^2.0.3+1
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.0
  image_editor: ^1.3.0
  settings_ui: ^2.0.2
  device_preview: ^1.0.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/