// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKbYn9WdUo6YFX_oJfjOr7tvhWUzYJqso',
    appId: '1:181081747320:web:89e5ee4cb33c3cea2fa28d',
    messagingSenderId: '181081747320',
    projectId: 'join-howdy',
    authDomain: 'join-howdy.firebaseapp.com',
    storageBucket: 'join-howdy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfSEgjW-6Z5RDv4aLKXJ_f12X5gFXVS0',
    appId: '1:181081747320:android:8ea52430ce027b932fa28d',
    messagingSenderId: '181081747320',
    projectId: 'join-howdy',
    storageBucket: 'join-howdy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYq5X4JFF43PoRXlcwrAGTpkVevC612yI',
    appId: '1:181081747320:ios:15a95b02cabbbf992fa28d',
    messagingSenderId: '181081747320',
    projectId: 'join-howdy',
    storageBucket: 'join-howdy.appspot.com',
    iosBundleId: 'one.orae.howdy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYq5X4JFF43PoRXlcwrAGTpkVevC612yI',
    appId: '1:181081747320:ios:a448eac1f30f3a3e2fa28d',
    messagingSenderId: '181081747320',
    projectId: 'join-howdy',
    storageBucket: 'join-howdy.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
